### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by titoiride** [ALaDyn/ALaDyn#83]
- AppVeyor fails on every configuration (seems a vcpkg building issue)
- Compilation error on MacOS - gcc@5 - openmpi configuration

In PR #82, MacOS - gcc@5 - openmpi configuration has been moved to allowed failures, while AppVeyor still fails. PGI compiler has been updated to 19.4 in commit 1d62d22.

**Comment by cenit** [comment]
when updating PGI to 19.4, did you update also the silent installer instructions, like described here?
https://www.pgroup.com/userforum/viewtopic.php?t=6352&sid=9d11c16bdf052ac299575aaa8481557e

**Comment by titoiride** [comment]
I think I did, because now it looks like this 

  - if [%COMPILER%]==[pgi] %WORKSPACE%\pgiws64-194.exe /s /f1"%WORKSPACE%\setup.iss"


but I don't know if it's enough. However, if you can, give it a look!

> on Mac, about gcc@5, we can remove it. It's now an abandoned configuration and it does not work anymore, like any other Homebrew's gcc, due to library mismatches

thank you, I'll remove Mac - gcc@5 configuration from the travis matrix!

**Comment by cenit** [comment]
what I mean is what follows the `#prepare the silent install for PGI`
It may require a full re-do, I will look for it

**Comment by cenit** [comment]
nope, it is just for VS users using it as their preferred IDE. We could even remove it now
